- components/embeding20/index.js
- components/lenta/index.js
- components/post/index.js
- components/share/index.js
- components/share/templates/url.html
- components/video/index.js
- js/functions.js
- js/satolist.js
- js/vendor/plyr.js
- proxy/pocketnet/functions.js
- proxy/pocketnet/satolist.js
> Peertube videos added to plyr player

- js/peertube-master.js
- Bug fixes
- Peertube Auth moved
> Various bug fixes 

- components/uploadpeertube/index.js
- components/uploadpeertube/templates/index.html
- js/functions.js
- js/peertube-master.js
- proxy16/peertube.js
- updated uploading logic
- fixed error handling
- fixed markup
> Peertube Views

- js/peertube-master.js
- Now on failed auth request client is trying to update existing access token
> Add token refreshing mechanics

- proxy16/lib/PeertubeServer.js
- proxy16/package.json
- proxy16/peertube.js
- PeertubeServer class added
- added timeout to listVideos call
> Optimize Proxy video requests

- components/streampeertube/index.js
- components/streampeertube/templates/index.html
- localization/en.js
- localization/ru.js
- auto-creating stream on button click
> Stream window logic changed

- js/peertube.js
> fix auth with specified host

- components/uploadpeertube/index.js
> Return link imports

- js/peertube.js
> Removed third host

- components/share/index.js
- components/share/templates/url.html
- js/peertube.js
- proxy16/peertube/index.js
- change preview image call errors logging
- change preview button appearance logic
> fixed wallpaper errors

- components/videoCabinet/index.js
- components/videoCabinet/templates/videoList.html
- Fixed preview paths 
- Fixed eternal loading of unreachable servers (or shutdown servers)
> Videos LazyLoad fixes

- components/videoCabinet/index.js
- components/videoCabinet/templates/metmenu.html
- Hid video button for posted videos
> Video Removing Restriction

- components/help/templates/guides.html
- components/videoCabinet/index.js
- localization/en.js
- Added Video node setup guide
- Added total views caching
> Video node setup guide

- proxy16/proxy.js
- Added gf110's server to proxy
> New user server

- js/peertube.js
- proxy16/proxy.js
> Added New Streming Server

- proxy16/peertube/index.js
- proxy16/peertube/instance.js
- Fixed automatic upload availability calculation function
> Fix server availability calculation

- components/authorization/templates/index.html
- components/pkview/index.js
Chrome browser is now supported.
> Ability to fast save private key

- components/uploadpeertube/index.js
- components/videoCabinet/index.js
- js/logger.js
- Added error codes
- Added payload body
- Fixed incorrect errors stringifying
- Fixed date formatting
> Logger updates

- components/imagegallery/index.js
- components/lenta/index.js
- components/post/index.js
- js/functions.js
Click outside of...
- ... photo, closes gallery window.
- ... article closes it.
- ... video window closes it.
> Outside click closes the window

- js/video-uploader.js
- c296d81835236a2fdfa84bdb78ec2641362252bd - Added chunk caching separation by user
- c296d81835236a2fdfa84bdb78ec2641362252bd - Caching active host of session to not break delayed upload
- b526033bcb08ca20596b97b294a975bb368945bc - light code sanity and optimizations
> Video uploader hot fixes

- js/file-hash.js
- 2bc7670e7d1e7293b993fbce0abaaade186776de - Added module export if called from **require()** or **import()**
> getUniqueFileId was not exported

- components/uploadpeertube/index.js
- js/peertube.js
- js/satolist.js
- New built-in auth route for test server
- Reworked error logs logic
> New auth route and logging logic

- js/polyfills.js
- 5c3ee2e3bb58148182582f6210d48e9cbd4a5b85 - Added **Textencoder** and **Textdecoder** polyfills for old browsers support
> Textencoder and Textdecoder polyfill

- proxy16/functions.js
- proxy16/node/applications.js
- tpls/main.js.tpl
Fixed notification event on click
> Fixed node permissions

- components/lenta/templates/share.html
- Fixed small bug that crashed repost action
> Small Repost Fix

- components/lenta/index.js
- components/post/index.js
-fixed pkoin button in article
> Boost button fix in article

- js/satolist.js
-Change complain transaction
-Added new flags
-Added new blocking rules
> User complain feature and blocking rules

- components/complain/index.css
- components/complain/index.js
- js/satolist.js
-Fix localization bug
-Change complain modal size
_This must resolve https://github.com/pocketnetteam/pocketnet.gui/issues/455#issuecomment-1141953477_
> User complain feature bug fix

- components/lenta/templates/metmenu.html
-updated complain permission logic
> Complain fixed permissions

- js/satolist.js
Add white list for accounts with reserved names
> Search results filtering optimization

- js/logger.js
> Fixed 'info' error

- components/uploadpeertube/index.js
- components/videoCabinet/index.js
- Changed errors stringifying method
> Proper errors stringifying

- components/uploadpeertube/index.js
- components/videoCabinet/index.js
- js/logger.js
- Moved error body formatting to the logger class
- Added new logging events to video cabinet
> Enhanced logging

- js/logger.js
- Changed location of error body stringifying for more robust performance
> small error logging change

- components/lenta/index.js
- components/recommendations/index.js
- components/registration/index.js
- js/logger.js
- js/satolist.js
- Added metrics for overall amount of session
- Added metric for overall video clicks
- Added metrics for stages of registration process
> Logger enhancement

- proxy16/proxy.js
Added two new video servers:
- peertube20.pocketnet.app (Germany)
- peertube21.pocketnet.app (US)
> Two new video servers

- .github/workflows/autotests.yml
- .github/workflows/build.app.yml
- .github/workflows/deploy.proxy.pre.yml
- .github/workflows/deploy.proxy.test.yml
- .github/workflows/deploy.proxy.yml
- .github/workflows/deploy.web.yml
- .github/workflows/pre.pocketnet.app.yml
- .github/workflows/test.pocketnet.app.yml
Author @andyoknen, I just separated the commits and created this pull to keep everything in flow.
- `vX.Y.Z` - electron builds and creates draft release
- `vX.Y.Z-web` - deploy production web
- `vX.Y.Z-proxy` - deploy production proxy
- `vX.Y.Z-proxy-test` - deploy prerelease proxy on [test.pocketnet.app](http://test.pocketnet.app/)
- `vX.Y.Z-proxy-pre` - deploy prerelease proxy on [pre.pocketnet.app](http://pre.pocketnet.app/)
- `vX.Y.Z-pre` - deploy prerelease web on [pre.pocketnet.app](http://pre.pocketnet.app/)
- `vX.Y.Z-test` - deploy prerelease web on [test.pocketnet.app](http://test.pocketnet.app/)
> Refactoring actions

- README.md
- Centered logo and title Readme.md
...
> docs: add logo to readme header

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/actions/build.macos.yml
- .github/workflows/build.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- SECURITY.md
- Template for pull requests
- Automatic assembly of pull requests with the label `deploy.dev` based on master
- Composite actions for organizing multi-level workflows
- Template for a bug report based on a form
It is necessary to describe these changes in the wiki or on the documentation site for review by the team
> refactoring: git workflow setup

- js/satolist.js
- Introducing tabs/windows synchronization mechanisms
- Created an example with switching UI theme on all open tabs/windows
This API works only for browser. Electron and Cordova related functionality MUST NOT use this API, as it is switched off there.
I provide the API for these mechanisms in the comments [here](https://github.com/pocketnetteam/pocketnet.gui/pull/601#issuecomment-1222063744). COULD be moved on documentation pages.
> feat: localstorage synchronizer mechanism

- proxy16/proxy.js
- peertube22.pocketnet.app
- peertube23.pocketnet.app
- peertube24.pocketnet.app
- peertube25.pocketnet.app
- peertube26.pocketnet.app
- peertube19mirror.pocketnet.app
> New peertube servers deploy

- components/lenta/index.js
- components/post/index.js
- js/logger.js
Added logging on different video playback errors. Logs are aggregated and sent no more than 1 time per minute.
Information:
- Connection type
- Resolution
- Video url
- Device
> Video stalling errors logging

- .github/workflows/delete.old.runs.yml
- Added new workflow scenarion
Not tested - need merge to master for testing
> workflow: delete old runs

- js/satolist.js
> patch: update limit's counter

- proxy16/node/control.js
- Removed old dependencies when downloading a node
> fix: easynode install new version

- components/comments/index.js
- components/lenta/index.js
- components/post/index.js
- js/satolist.js
> fix comment banner

- components/accounts/index.js
- components/statistic/index.js
- components/ustate/index.js
- js/satolist.js
> fix limits and statistic

- package.json
> Set version to 0.8.11

- components/lenta/templates/groupshares.html
- components/lenta/templates/shares.html
> fix: add rendered class to videos

- proxy16/kit.js
> fix: clear inactive test nodes

- README.md
> docs: add badge icons in readme

- components/lenta/index.js
- components/recommendations/index.js
- components/registration/index.js
- js/app.js
- js/logger.js
- js/satolist.js
- User registration steps logging
- Video load with recommendations list logging
This pull request is the rebased and actualized version of lost #548 authored by @zanhesl.
> feat: extra logging

- components/test/index.js
- js/kit.js
- The ability to edit the profile has been added for reserved accounts,
> patch: Editing reserved accounts

- proxy16/node/control.js
- Removed old dependencies when downloading a node
This pull request is continue of #664
> fix: easynode source link

- js/lib/client/api.js
Added small log, which is sent when an rpc call fails.
> patch: rcp calls logging

- cordova/package.json
> hotfix: cordova run app in background plugin

- package.json
> fix: update version in package.json

- .github/workflows/night.test.bastyon.com.yml
- package.json
> workflow: create night.test.bastyon.com.yml

- components/camerapreview/index.js
- css/main.css
- css/main.less
- js/app.js
- js/functions.js
- js/satolist.js
- package.json
> fix: virtual keyboard api, camerapreview optimizations, gifs

- components/registration/index.js
- js/satolist.js
> bloggers update

- package-lock.json
- package.json
> patch: set version to 0.8.17

- proxy16/proxy.js
- Added two new video servers
...
> patch: two new video servers

- cordova/resources/android/splash/splash-screen-logo.xml
- tpls/config.xml.tpl
Fix the splash screen for Android (was displaying a white circle on some devices).
> Cordova android: Fix splash screen (white circle issue)

- js/main.js
- package.json
- Fix use of variable `_listofproxies`
- Set version to **0.8.20**
Invalidly used `_listofproxies` variable in **js/main.js**
> hotfix: invalid named variable used

- components/comments/index.js
- components/usersettings/templates/index.html
- js/app.js
- js/satolist.js
- proxy16/kit.js
- proxy16/node/notifications.js
- proxy16/node/notificationsDictionary.js
- proxy16/node/wss.js
- tpls/index.html.tpl
Push notifications node server change. However, there are some other small fixes present in the PR.
> patch: push notifications node server change

- js/satolist.js
Simply change an error message to be more user friendly.
> patch: informative error for no video data

- components/post/index.css
- components/post/index.less
- js/main.js
- js/peertube.js
- js/satolist.js
- js/video-uploader.js
- package.json
- proxy16/cli.js
- proxy16/logger.js
- proxy16/node/notifications.js
- proxy16/proxy.js
- proxy16/server/firebase.js
- Push notification functionality fixes
- Push notifications functionality introduced in #621 and merged in `master` at c44d9bd8612d310ba30da368ee296c41b3936172 is marked as not ready and temporarily disabled.
> patch: disable new push notifications functionality

- js/satolist.js
- package.json
- Add **Stanislav_Grechka** to verified users
- Add **3rm** to verified users
- Add **Arigrad** to verified users
> patch: add new verified users

- README.md
```diff
+ This project is tested with BrowserStack.
```
> docs: add browserstack text to readme

- components/registration/index.css
- components/registration/index.less
- Fix subscription button styles
> fix: recommendations banner button width

- components/registration/index.js
- Remove **SobiNews** from recommended bloggers on English branch.
> patch: remove recommended bloggers from english branch

- js/user.js
- package.json
> fix: private key not showing

- components/main/index.js
- js/satolist.js
- Fix recommendations not showed
This PR is continuation of #747
> fix: recommendations load on post open try 2

- components/main/index.js
- [Change  main lenta request]
> patch: top ranked videos instead of most commented

- components/camerapreview/index.css
- components/camerapreview/index.js
- components/camerapreview/index.less
- components/camerapreview/templates/index.html
- js/app.js
- js/functions.js
- js/satolist.js
- package.json
> patch: use android gallery for image upload

- js/satolist.js
- package.json
> fix: iphone notifications

- js/satolist.js
- package.json
> patch: packet 779

- components/lenta/index.css
- components/lenta/index.less
- components/lenta/templates/sharearticle.html
- css/common.css
- css/common.less
> patch: article text part in preview

- js/app.js
> patch: disable popups for test environment

- components/editVideoDescription/index.css
- components/editVideoDescription/index.js
- components/editVideoDescription/index.less
- components/editVideoDescription/templates/index.html
- components/videoCabinet/index.css
- components/videoCabinet/index.js
- components/videoCabinet/index.less
- js/_map.js
- tpls/index_el.html.tpl
- Fix vendor path bug in one of the libraries (index_el)
- Reworked video description editing window to separate component
- Fixed z-index bug with tags menu during video description editing
...
> fix: video description editing

- js/satolist.js
* `PDSkBPfxgX25RTde3VzoZ1Wz8yTeUaYAvM` [**Velitsko**](https://bastyon.com/velitsko)
* `PFkCWH4zuAYtVJSQn6rvgEiSsMjHvN8dwE` [**Brigadier**](https://bastyon.com/brigadier)
* `PSbFTgRftgSCsTzTdYFWY6SYkPD72Pdqfx` [**KONSPIROLOG_**](https://bastyon.com/konspirolog_)
* `PXZGt2EaVyRDrXCWMTiH2Tvh5eP7RZhhxF` [**aliexpress_club**](https://bastyon.com/aliexpress_club)
* `PCtDTH7XznLBCTHhKFeeg8ezSa7WJtYiMJ` [**TelekanalStalingrad**](https://bastyon.com/telekanalstalingrad)
> patch: add new confirmed users

- js/app.js
- js/main.js
- js/satolist.js
- localization/de.js
- localization/en.js
- localization/es.js
- localization/fr.js
- localization/it.js
- localization/kr.js
- localization/ru.js
- localization/zh.js
- package.json
> patch: remove pocketnet redirect banner

- minimize.js
- package.json
- tpls/manifest.json.tpl
- [...]
This PR is related to #811 and fixes some errors.
> fix: meta configs introduced in PR 811

- .gitignore
- js/functions.js
- js/kit.js
> feat: share long post in mobile app

- components/editVideoDescription/index.css
- components/editVideoDescription/index.less
- components/editVideoDescription/templates/index.html
- Changed markup for mobile and desktop devices for "Edit video name/description" section in "My videos" component.
> fix: text editing window markup

- components/bastyon_iphone/index.css
- components/bastyon_iphone/index.less
- Fix styles
Some patches related to https://github.com/pocketnetteam/pocketnet.gui/pull/805.
> patch: invitation to install pwa application on ios styles

- components/registration/index.css
- components/registration/index.less
- fixed registration bloggers - uniq height for each; text always into container 
...
> fix: registration_bloggers_styles

- .github/workflows/build.release.yml
- Modify release workflow to support better titles
Better release action title, e.g. **`Release v0.8.36`**, **`Release v0.8.36-beta3`**
> repo: action better release title

- components/welcome/index.js
- js/navn.js
- js/satolist.js
- navn.js handles link with welcome and params
This PR closes #735
> patсh: parse link and open chat

- .github/workflows/build.dev.yml
- .github/workflows/build.release.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
- package.json
- Added support RPM installer
Need testing
> feat: rpm binaries support

- .github/workflows/night.bastyon.com.yml
> feat: rpm support

- components/nodecontrol/templates/nodecontentmanage.html
> fix: minimum requirement ssd space

- js/kit.js
> fix: share link with image

- .github/workflows/analyze-conflicts.yml
- Add `analyze-conflicts.yml`
- Using [shpingalet007/conflictor](https://github.com/shpingalet007/conflictor) action to construct schema of conflicts.
This PR introduces support of marked PR's analysis. This allows to easily understand between which of them conflicts are happening and resolve them faster.
The action produces artifacts with graphic schema of conflicts and JSON debug stats.
> repo: workflow for conflicts analysis

- components/applications/index.css
- components/applications/index.js
- components/applications/index.less
- components/camerapreview/index.css
- components/camerapreview/index.js
- components/camerapreview/index.less
- components/comments/index.js
- components/comments/templates/post.html
- components/menu/index.css
- components/menu/index.js
- components/menu/index.less
- components/menu/templates/index.html
- components/mobilesearch/index.js
- js/functions.js
- js/image-uploader.js
- js/satolist.js
- tpls/config.xml.tpl
- tpls/main.js.tpl
> patch: application icon menu and cordova camera

- js/satolist.js
- conditions for access to mass mailing in chat (for certain users)
> patch: mass mailing access conditions

- components/pkview/index.css
- components/pkview/index.less
- fixed popup with key words after register for mobile devices (showed all 12 words)
...
> fix: mnemonic phrase popup on mobile

- js/logger.js
- proxy16/peertube/roy.js
- Fixed video server changing process on the proxy, archive now successfully functions
- Fixed logs sending
...
> fix: Proxy Video Server change & Logger

- js/image-uploader.js
- js/main.js
- package.json
> patch: remove peertube uploading

- js/kit.js
- Fixed #916 
... This PR is closed #916
> fix: empty donation addresses

- js/image-uploader.js
- Servers for image uploading now are selected in the same way as for videos. Selection now respects an amount of free space on the server.
...
> patch: server selection for image upload

- components/comments/index.js
- components/comments/templates/metmenu.html
- Enable author of post to delete all comments
This PR is closed https://bastyon.atlassian.net/jira/software/projects/BAS/boards/1?selectedIssue=BAS-12
> feat: ability to delete all post comments by author

- components/easynode/index.js
- [...]
This PR is closed https://bastyon.atlassian.net/browse/BAS-24
> patch: staking profit formula update

- components/pkoin/index.css
- components/pkoin/index.js
- components/pkoin/index.less
- components/pkoin/templates/boostinfo.html
- [...]
This PR is closed https://bastyon.atlassian.net/browse/BAS-32
> patch: boost page always show audience reach

- components/share/index.js
- components/share/templates/postline.html
- components/streampeertube/index.js
- components/videoCabinet/templates/index.html
- js/peertube.js
- js/satolist.js
- Added streams option for postline
- Streams have their own url postfix
...
> patch: Add streams for testnet

- js/functions.js
- js/kit.js
- js/satolist.js
- Added itisstream function, which helps to define whether a video is a stream or not
- Fixed stream display in feed and post for roys with multiple servers
...
> Stream detecting function and fix

- components/leftpanel/templates/footer.html
- [...]
This PR is closed https://bastyon.atlassian.net/browse/FBUG-17
> fix: Leftpanel minor fixes

- components/activities/index.js
> hotfix: show answers in comments block

- js/satolist.js
> patch: pass fa icons into chat

- components/pkoin/index.css
- components/pkoin/index.less
- [...]
This PR is closed https://bastyon.atlassian.net/browse/FBUG-20
> fix: boost page styles

- components/system16/index.js
- components/system16/templates/webserveradmin.html
- components/transportsmanagement/templates/settings.html
- css/common.css
- css/common.less
- css/main.css
- css/main.less
- localization/de.js
- localization/en.js
- localization/es.js
- localization/fr.js
- localization/it.js
- localization/kr.js
- localization/ru.js
- localization/zh.js
- proxy16/kit.js
- proxy16/node/torcontrol.js
- proxy16/proxy.js
- proxy16/transports.js
- Fix TOR starting multiple instances at once on restart
- Add 2 seconds before starting new instance
- Handle SOCKS5 errors in requests
- Mark poketnetpeertube.ru offline
- Add localization on all languages
- Add OBFS4 bridges support. Can be provided in settings (not in widget yet)
- Fix video download loading bar interface
> patch: application network transport system

- components/donations/index.js
This PR is closed https://bastyon.atlassian.net/browse/BAS-60
> fix: donations page localization change issues

- components/system16/index.js
- components/transportsmanagement/templates/settings.html
- js/app.js
- package-lock.json
- package.json
- proxy16/kit.js
- proxy16/node/applications.js
- proxy16/node/torcontrol.js
- proxy16/package-lock.json
- proxy16/package.json
- Tor builds repository changed to [shpingalet007/tor-builds](https://github.com/shpingalet007/tor-builds)
- Arch dependent Tor bundles
- Some external hosts are whitelisted to not pass via Tor: Brighteon, Vimeo, Youtube, Bitchute
- OBFS4 interface protection from user errors in input
- Hide Tor settings if disabled
> fix: application network transport system

- proxy16/package-lock.json
- proxy16/package.json
- proxy16/peertube/instance.js
- proxy16/transports.js
- Not parsing JSON response with `await res.json()` due to some bug. Using legacy `JSON.parse(await res.text())`
- Update node-fetch to 3.3.1 (latest). Using `import()` to use ESM.
> hotfix: proxy server shuts down on invalid response

- .github/workflows/deploy.pulls.dev.yml
- Flag `-run` was called in invalid way
- Patched value to serve the pre deploy needs
> fix: build version badge for pre deploy

- proxy16/ipc.js
- proxy16/node/torcontrol.js
- Fix code error after #983
- Remove repeating tor binaries fs checks
Made in context of #873.
> fix: error in ipc and tor installed checks

- components/comments/index.css
- components/comments/index.less
This PR is closed https://bastyon.atlassian.net/browse/FBUG-21
> patch: show answers for blocked comments

- js/peertube.js
- Fix stream link creation if one already exists on server
...
> Fix stream creation if one already exists

- components/comments/index.js
- components/donate/index.js
- components/donate/templates/index.html
- components/pkoin/index.js
- js/satolist.js
This PR is closed https://bastyon.atlassian.net/browse/BAS-68
> patch: set minimal boost to 0.1

- components/share/templates/url.html
- localization/en.js
- localization/ru.js
This PR is closed https://bastyon.atlassian.net/browse/FBUG-24
> patch: better locale for audio post stats

- proxy16/proxy.js
- Archived servers 4,5,6,9. Added them to upload instead of mirrors.
...
> patch: Archived part of the servers

- proxy16/proxy.js
> hotfix: enable mirror servers 

- components/donations/index.js
This PR is closed https://bastyon.atlassian.net/browse/BAS-69
> feat: ability to donate project with pkoin

- cordova/cordova-plugin-ionic-keyboard/src/android/CDVIonicKeyboard.java
> fix: Update CDVIonicKeyboard.java

- proxy16/proxy.js
> patch: add new peertube servers and mark some old

- components/activities/index.css
- components/activities/index.js
- components/activities/index.less
- components/activities/templates/content.html
- components/activities/templates/index.html
- components/menu/index.js
- js/functionsfirst.js
- js/satolist.js
- js/vendor/jquery.js
> patch: activities, notifications, fastsearch, jquery update

- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/night.bastyon.com.yml
- cordova/build.tpl.json
- js/app.js
- js/satolist.js
- minimize.js
> patch: add gf apk

- .github/workflows/night.bastyon.com.yml
> fix: night deploy workflow

- js/functions.js
- js/kit.js
> patch: pinfo classes

- components/share/templates/postline.html
- js/functions.js
- js/satolist.js
- localization/ru.js
> fix: shares, livestream

- components/share/index.css
- components/share/index.js
- components/share/index.less
- components/share/templates/postline.html
- js/functions.js
- localization/ru.js
> fix: base64 in images and css rules share

- components/categories/index.css
- components/categories/index.less
- components/howtobuy/index.css
- components/howtobuy/index.less
- components/leftpanel/templates/footer.html
- localization/en.js
- localization/ru.js
- This PR is closed https://bastyon.atlassian.net/browse/BAS-75
> fix: left footer, left panel styles, how to buy page

- css/main.css
- css/main.less
- js/satolist.js
- This PR is closed https://bastyon.atlassian.net/browse/FBUG-25
> fix: video back button area

- components/share/index.js
- js/vendor/plyr.js
- Use Cloudflare IPFS gateway instead of ipfs.io
The reason for this change is the lack of speed of ipfs.io. It responds x10 slower than Cloudflare, so this will improve performance in creating IPFS posts, and will probably reduce the number of cases when the gate is inaccessible.
> patch: faster ipfs gateway

- components/lenta/templates/share.html
- components/share/templates/url.html
- js/vendor/plyr.js
- package-lock.json
- Use first photo added to the post as IPFS video thumbnail
Not the most beautiful solution, however it would serve the needs for now
> feat: ipfs video thumbnail support

- proxy16/proxy.js
- Servers **group 10** is archived
- Servers **group 12** is archived
- Servers **group 36** is archived
Archive server **peertube.archive.pocketnet.app** used
> patch: peertube servers list

- proxy16/proxy.js
- Log address of node that was responsible for it
- Log block number where transaction was written
> patch: transactions logs add more details

- .github/workflows/deploy.proxy.yml
- js/main.js
- js/openapi.js
- Remove proxies 4 and 5 from code
- Remove proxies 4 and 5 from deploy
Proxies 4 and 5 are offline now
> patch: proxies list update

- proxy16/proxy.js
- Fix shadowed node object
Related to #1045
> hotfix: transaction logs shadowed node object

- proxy16/proxy.js
- Removed second test server
...
> patch: peertube test servers list

- minimize.js
- Using git command to get SHA of commit from which build is done
Related to #947
> patch: version badge sha autofill

- proxy16/peertube/instance.js
- proxy16/proxy.js
- Servers group 21 is archived
- Increased stats interval time up to 30 minutes
> patch: peertube servers list and stats interval

- proxy16/proxy.js
- Added new dedicated server for bloggers and streaming
...
> patch: dedicated peertube server for verified users

- js/peertube.js
- proxy16/proxy.js
- Server updates
- Dedicated condition update
> patch: peertube servers list and dedicated conditions update

- components/videoCabinet/index.js
- js/satolist.js
- Fixed unposted videos section — if video is broken is does not show
If the user has no broken videos in cabinet, he still can test the PR running in console. `---YOUR-ADDRESS---` must be replaced with user account address.
```js
localStorage.unpostedVideos = {"---YOUR-ADDRESS---":["peertube://peertube35.pocketnet.app/e70f6569-bed4-402a-aa5b-1eb2558b6a2b", "peertube://peertube35.pocketnet.app/asdasd", "", "asdasdsadasdasdsa", "peertube://peertube35.pocketnet.app/e70f6569-bed4-402a-aa5b-1eb2558b6a2b"]}
```
> fix: not posted videos not disappearing in video cabinet

- components/uploadpeertube/index.js
- components/videoCabinet/index.js
- js/peertube.js
- Expired videos (21 days+ old) are now hidden (fixed)
- Full video description now correctly loaded (try with huge descriptions)
- .mkv files now pass frontend validation on upload
This PR is doing some work related to the PR #1058 and others.
> fix: some issues in cabinet

- components/uploadpeertube/index.js
- js/functions.js
- js/polyfills.js
> fix: matroska video upload

- proxy16/kit.js
> feature: added 0.22-alpha test node

- tpls/index_el.html.tpl
> hotfix: linkify library in electron

- README.md
- Latest download links in readme was broken. Fixed.
> repo: update broken latest links in readme

- js/_map.js
- js/broadcaster.js
- js/satolist.js
- Moved TOR Broadcaster initializator call
Related to changes after #911
> fix: tor broadcaster not being started

- js/functions.js
- js/module.js
- js/satolist.js
> fix: window spinner

- components/commentBanner/index.js
- components/lenta/index.js
- components/post/index.js
> fix: missing comment banner

- .github/workflows/analyze-conflicts.yml
- .github/workflows/deploy.proxy.yml
- .github/workflows/deploy.pulls.dev.yml
- Update  **shpingalet007/conflictor@v0.3.1** ➜ **shpingalet007/conflictor@v0 (v0.3.4)** module for conflicts analysis between pulls on our flow
- Update **docker/metadata-action@v3** ➜ **docker/metadata-action@v4**
- Update **docker/login-action@v1** ➜ **docker/login-action@v2**
- Update **docker/setup-buildx-action@v1** ➜ **docker/setup-buildx-action@v2**
- Update **docker/build-push-action@v2** ➜ **docker/build-push-action@v4**
...
> repo: workflows update

- components/about/index.js
- components/comments/index.css
- components/comments/index.js
- components/comments/index.less
- components/main/index.js
- components/welcome/index.js
- js/app.js
- js/functions.js
- js/functionsfirst.js
- js/lib/client/sdk.js
- js/satolist.js
- package.json
- tpls/config.xml.tpl
> fix: navigation bar color and images

- components/share/index.js
- components/share/templates/postline.html
- components/streampeertube/index.js
- components/streampeertube/templates/index.html
> feat: add stream for "shark" users

- proxy16/dockerfile
> Change launch entrypoint to cmd

- proxy16/dockerfile
> Update node to 16 version in docker

- proxy16/dockerfile
> In docker changed cmd to entrypoint

- js/peertube.js
- proxy16/proxy.js
- Fixed developers addresses not getting bloggers server
- New Server
...
> fix: special and archive server

- js/peertube.js
- proxy16/peertube/roy.js
- proxy16/proxy.js
- Added true host parameter after video upload to fix issues with archived server — previously one could have loaded a video via ip and could have gotten the wrong link thus making the video impossible to watch
- Fixed associated peertube5new issue — error videos now available
...
> fix: situations when original server was archived

- proxy16/peertube/roy.js
- proxy16/proxy.js
- Fixed proxy output for 51 server
...
> Fix 51 server proxy output

- proxy16/peertube/instance.js
- proxy16/proxy.js
> 41 server and free space

- proxy16/proxy.js
> 70-80-srvs

- js/functions.js
> fix: images upload, add try catch

- js/functions.js
- js/satolist.js
- If the server on which image is uploaded is now archived, the link is changed correspondingly
...
> Images archiving path

- proxy16/proxy.js
> Archived 17 server

- proxy16/proxy.js
> Servers 90-100

- .github/workflows/deploy.pulls.dev.yml
- Add missing **google-services.json** for pre-deploy workflow
Related to #1122
> repo: add firebase config for pre-deploy workflow

- components/menu/index.js
- components/menu/templates/index.html
- js/functions.js
- js/satolist.js
- [[...]](https://bastyon.atlassian.net/browse/BAS-87)
This PR is closed https://bastyon.atlassian.net/browse/BAS-87
> feat: christmas_theme_2023

- components/menu/index.css
- components/menu/index.less
- package.json
- Fixed bug on user page: https://github.com/pocketnetteam/pocketnet.gui/pull/1157
... This PR is closed https://github.com/pocketnetteam/pocketnet.gui/pull/1157
> Fix: christmas theme

- .github/workflows/deploy.branch.dev.yml
> repo: add ability to deploy specific branch for workflow

- .github/workflows/deploy.branch.dev.yml
- Fix dependency issue
Related to PR #1164
> repo: fix branch deploy workflow

- proxy16/proxy.js
- 32 34 35 servers archived
...
> 32 34 35 servers archived

- js/satolist.js
- proxy16/peertube/roy.js
- proxy16/proxy.js
- Servers to achived images list
- Proxy fix
...
> Images Archive and video fix

- proxy16/peertube/index.js
> Fix stream red

- package-lock.json
- package.json
- Set package version to 0.8.77
> patch: set package version to 0.8.77

- components/lenta/index.js
- components/post/index.js
- js/functions.js
- Fix cursor dragging leading to post close. Reported closing post with not sent comment
> fix: cursor dragging leading to post close

- components/userslist/index.css
- Fix user icons spacing issue in profile
Related to PR #1119
> fix: user icons spacing issue in profile

- js/lib/client/sdk.js
- Fix negative reputation showed as zero
Related to PR #911
> fix: negative reputation showed as zero

- components/menu/index.css
- components/menu/index.js
- components/menu/index.less
- components/menu/templates/index.html
- js/functions.js
-  This PR is closed https://bastyon.atlassian.net/browse/BAS-88
> Feat: remove christmas theme

- .github/workflows/night.test.bastyon.com.yml
- Fix night test web deploy using Node.js of version 14. Using 16 now.
> repo: fix night test web deploy

- components/activities/index.js
> fix: changing the way to determine the end of scrolling of the activity container

- proxy16/node/torcontrol.js
- Update Snowflake STUN list.
- New working Snowflake bridges from official TOR browser application.
- UpdateBridgesFromAuthority flag is removed.
> patch: tor snowflake bridges configurations

- js/lib/client/p2pvideo.js
- proxy16/node/torcontrol.js
- Set new STUN servers for general and TOR uses
- Set new TURN servers
> patch: update stun/turn list

- package-lock.json
- proxy16/node/torcontrol.js
- Reduce STUN list size <510 bytes due to limits of TOR
- NPM audit fixes
Related to PR #1193
> patch: npm audit fixes and tor stun limits

- js/lib/apps/index.js
- js/lib/apps/sdk.js
> Add vote method for barteron

- proxy16/node/manager.js
- Set default value if sws prop is not defined
Related to PR #1179
> fix: missing sws prop in nodes file

- package-lock.json
- electron-builder (CVE-2024-27303)
- jose (CVE-2024-28176)
Fixed automatically with `npm audit fix`
> patch: vulnerable dependencies fixes

- proxy16/exchanges.js
- Add Coingecko as aggregated ticker provider
This change allows us to get actual PKOIN rate without adding new exchange platforms directly to our code base. This work is done very well by Coingecko and is available through their API
> feat: coingecko pkoin aggregated rate

- .github/workflows/build.dev.yml
- .github/workflows/deploy.branch.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
- Add missing Proxy16 build stage after NPM install
Related to PR #1175.
> patch: add missing proxy16 build stage

- package.json
- proxy16/dockerfile
This reverts commit a2a4027.## Standards checklist:
- PR #1222 is invalidated and reverted
- Fix action-electron-builder build script
Related to PR #1175
> hotfix: remote peertube list support for electron builder flow

- .github/workflows/deploy.pulls.dev.yml
- Fix pull requests deploy for macOS
> repo: fix pull requests deploy for macos

- README.md
> repo: update market badges

- .github/workflows/deploy.pulls.dev.yml
- js/electron/transcoding2.js
- minimize.js
- package-lock.json
- package.json
- Fix final transcoding result not being renamed due to FS permission issues
- Replace NPM module `html-minifier` with `html-minifier-terser` due to CVE-2022-37620
- Replace deprecated `fs.rmdirSync(...)` with `fs.rmSync(...)`
> fix: transcoding file permissions

- package.json
- Setting Electron Builder to build hybrid application that supports both x64 and arm64
Tested on my fork
> repo: build hybrid arch application

- .github/PULL_REQUEST_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE/DOCUMENTATION.md
- .github/PULL_REQUEST_TEMPLATE/FEATURE.md
- .github/PULL_REQUEST_TEMPLATE/FIX.md
- .github/PULL_REQUEST_TEMPLATE/HOTFIX.md
- .github/PULL_REQUEST_TEMPLATE/MAINTANANCE.md
- .github/PULL_REQUEST_TEMPLATE/MAINTENANCE.md
- .github/PULL_REQUEST_TEMPLATE/PATCH.md
- .github/PULL_REQUEST_TEMPLATE/REFACTORING.md
- Add template selection page
- Add **Feature** template
- Add **Patch** template
- Add **Fix** template
- Add **Hotfix** template
- Add **Maintenance** template
- Add **Documentation** template
- Add **Refactoring** template
This PR introduces pull request templates, enabling better management and organization of PRs by the team. By selecting the appropriate template, contributors can clearly indicate the nature of their changes, ensuring streamlined review and processing.
🚩 You can check the demo on [my fork](https://github.com/shpingalet007/pocketnet.gui).
> repo: templates for pull requests

- js/app.js
> fix: popups localization

- js/kit.js
Allow Offer to be published or not
> feat: fill here the pr title

- proxy16/kit.js
- tpls/main.js.tpl
> patch: set check updates every 1 hour

- .github/workflows/deploy.pulls.dev.yml
> patch: fill here the pr title

- js/lib/apps/index.js
- js/lib/apps/sdk.js
- localization/en.js
- localization/ru.js
> feat(apps): add permission and method for opening external links

- components/application/index.js
- components/devapplication/index.css
- components/devapplication/index.js
- components/devapplication/templates/example.html
- components/devapplication/templates/index.html
- components/devapplication/templates/miniAppDetail.html
- components/devapplication/templates/miniAppEditForm.html
- js/lib/apps/index.js
- js/lib/apps/sdk.js
- localization/en.js
- localization/ru.js
- package-lock.json
- pnpm-lock.yaml
> feat: devapps

- components/devapplication/index.js
- components/devapplication/templates/miniAppDetail.html
>  fix(devapplication): correct geting useraddres and application @DaniilKimlb

- config/Bastyon.json
> chore: add blockexplorer mini-app to config

- js/lib/apps/index.js
> feat: add name filter to applicationsSearch

- js/lib/apps/sdk.js
> feat: integrated makeURLHash method into SDK with encapsulation

- nginx.conf
> feat: example of nginx configuration

- package.json
> feat: add aur support

- .github/workflows/deploy.pulls.dev.yml
> fix: combine pulls action

- package.json
- share/applications/bastyon.desktop
> Add .desktop file for linux

- .github/workflows/build.release.aur.yml
> feat: workflow for releasing AUR application

- .github/actions/build.macos.yml
- .github/workflows/build.dev.yml
- .github/workflows/deploy.branch.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/deploy.web.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
> chore: Update GitHub Actions artifact upload to v4

- .github/workflows/build.dev.yml
- .github/workflows/deploy.branch.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/deploy.web.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
> chore: Update GitHub Actions download-artifact to v4 across workflows

- js/lib/apps/index.js
- package.json
> feat: add transactionsApiVersion

- .github/workflows/build.release.aur.yml
> fix: fill here the pr title

- .github/workflows/build.release.aur.yml
> fix: aur deploy action

- .github/workflows/build.release.aur.yml
> hotfix: fill here the pr title

- .github/workflows/build.release.aur.yml
> hotfix: aur deploy

- components/wallet/templates/stake.html
- config/Bastyon.json
- localization/en.js
- localization/ru.js
Changed wpkoin link and textes.
> wpkoin edit

- components/easynode/index.css
- components/easynode/index.less
- components/easynode/templates/index.html
- components/registration/index.css
- components/registration/index.less
- localization/en.js
- localization/ru.js
Added pkoin.basyon.app link to easynode page & fixed styles of next buttons on bloggers register page.
> easynode pkoin link & mobile fix

- .github/workflows/test.pocketnet.app.yml
> fix: upgrade nodejs

- config/Bastyon.json
- js/kit.js
- js/lib/apps/index.js
> fix: delivery test

- components/requestpermission/templates/index.html
- js/faq.js
> FAQ node 150 GB; receiver's amount payment. 

- js/lib/apps/index.js
- js/lib/apps/sdk.js
> feat(miniapp): add param address for channel

- proxy16/proxy.js
> fix: add init miniapp in proxy

- components/socialshare2/index.js
- components/socialshare2/templates/index.html
- js/lib/apps/index.js
- js/lib/apps/sdk.js
- js/satolist.js
- localization/en.js
- localization/ru.js
> feat: share on bastyon from barteron

- .github/workflows/deploy.branch.binaries.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
> Update GitHub Actions workflows to use ubuntu-latest instead of ubuntu-20.04 for Android builds

- .github/workflows/night.bastyon.com.yml
> Update GitHub Actions workflows to use ubuntu-22.04 for Android builds

- .github/workflows/analyze-conflicts.yml
- .github/workflows/build.release.yml
- .github/workflows/delete.old.runs.yml
- .github/workflows/deploy.branch.binaries.dev.yml
- .github/workflows/deploy.branch.web.dev.yml
- .github/workflows/deploy.proxy.pre.yml
- .github/workflows/deploy.proxy.test.yml
- .github/workflows/deploy.proxy.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/deploy.web.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
> Update GitHub Actions workflows to use ubuntu-22.04 for all jobs

- js/lib/apps/index.js
> fix(apps): register message listener early

- components/application/index.js
- components/application/templates/frameremote.html
- js/lib/apps/index.js
> feat: add iframe allow attributes based on granted permissions

- js/lib/apps/index.js
> feat(apps): emit permissionchange and notify minis

- js/lib/apps/index.js
> fix(apps): limit manifest and asset cache to 2 hours

- proxy16/node/torcontrol.js
This fixes the race condition that caused multiple Tor instances to be created. Multiple Tor instances cannot run with the same configuration, which eventually leads to a non-working Tor state.
...
> fix: prevent creation of multiple tor instances

- js/lib/apps/index.js
- js/lib/apps/sdk.js
- js/satolist.js
> feat: add methods for getting feeds and video posts SDK

- components/complain/index.js
- js/lib/apps/index.js
- js/lib/apps/sdk.js
> feat: add barteron complain feature

- components/system16/index.js
- proxy16/kit.js
- proxy16/node/torcontrol.js
This fixes the invalid message that Tor is not installed. It also fixes the indication of Tor installing and reinstalling.
...
> fix: tor is not installed

- components/transportsmanagement/templates/stats.html
- proxy16/transports.js
These changes introduce several improvements to automatic mode, such as falling back to a direct connection when Tor fails and robust host reachability checking. Also fixed displaying usage statistics and using the correct interval to recheck a host for reachability.
...
> feat: direct connection if tor fails

- js/lib/apps/index.js
> build: disable icon caching

- components/menu/index.css
- components/menu/index.less
- components/menu/templates/index.html
> fix(android): align the tor icon

- js/app.js
This reduces the minimum keyboard size to avoid unnecessary empty space above the keyboard if it has a short height.
...
> fix: reduce the minimum keyboard size
