pocketnetteam/pocketnet.gui

- js/satolist.js
- Wallet addresses are cached in LocalStorage.
- Wallet addresses are kept separate for each user.
- No conflicts awaited, as `sdk.addresses.storage.addresses` structure stays the same.
- Keys for each address requested only if app needs them.
- Once keys are requested, they will stay until app not closed.
- Code a little cleaned and optimized.
> Wallets credentials LocalStorage cache

- components/lenta/index.js
Video deletion on "Saved" page was killing the electron app
Object `players` was an empty object. When trying to read `players[id]` it is `undefined`.
> Fix app dying when video deleted

- js/peertube.js
- js/satolist.js
New built-in-server authorisation path (instead of the peertube plugin) for the test accounts
- Dynamically added new path for the test accounts (ready for production)
> Test accounts authorization route

- package-lock.json
- package.json
- proxy16/node/applications.js
- 236178e Awaiting **`Promise<Request>`**
```diff
- let req = proxy.transports.request(...)
+ let req = await proxy.transports.request(...)
```
- ea05240 When download canceled, it was producing message "Internal error". Fixed.
> Transports request was not awaited

- proxy16/node/applications.js
I didn't understand why the async request from proxy16/transports causes a memory leak - perhaps it's worth paying attention to this in order to use the TOR to download large files
> Fixed a memory leak when loading a snapshot database of a Node 

- proxy16/proxy.js
- Yandex-hosted servers (peertube 17, 18, 19) removed from downloading
- peertube19mirror activated again
> New Videos servers formation

- components/share/index.css
- components/share/index.less
- components/share/templates/url.html
- css/common.css
- css/common.less
There was no ability to look on which peertube server is video hosted. Sometimes, when we check the issues, we need to know this as fast as possible.
I made some UI changes into the player, that allows us to look this info from accounts added to test list.
_Related to pocketnetteam/bastyon-chat/pull/42_
> Show where is video hosted

- js/satolist.js
- Returned lost verified users entries
Some verified users were suddenly removed from verified list. It was occurred due to some list optimization (there were duplicated entries). In this pull request, I return them.
- SekretyPodnebesnoy
- Rostislav_z
- slavradio
- timcast_irl
- tim_pool
- RedPill78
> fix: return by error removed verified users

- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/pre.pocketnet.app.yml
- .github/workflows/test.pocketnet.app.yml
- Night platforms build added (copy & paste from deploy.pulls.dev.yml)
- Separate directories in dev.pocketnet.app/binaries: dev, night and test
> feat: night platform builds

- components/system16/index.css
- components/system16/index.less
- Node address row width no limited now inside `User settings > System`
> fix: width limits for node address row

- proxy16/proxy.js
> change simple slideAdminHash with sha256

- .github/workflows/build.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
- This reverts commit 4fa8367
Java 11 is crashing Github Actions. Currently, downgrading it...
> workflow: downgrade from java 11 to java 8

- js/transports/proxified-fetch.js
- js/transports/proxified-fetch.ts
- js/transports/tsconfig.json
* c96a4cc - add typescript config for **js/transports** sources
* b15fb3b - code missing in **proxified-fetch** sources fix
* e18af4a - macOS electron app produce errors on quit fix
This PR fixes macOS Electron app issue. When user tries to quit the app from the menu, it produces errors related to **proxified-fetch** mechanism. Found and fixed.
> fix: macos errors on electron app quit

- package.json
- Set cordova version code to 180203
> hotfix: set valid cordova version code

- components/menu/index.css
- components/menu/index.less
- css/main.css
- css/main.less
- 6037f0b - Add fallback for CSS3 `max(...)` via `@supports`.
- 451edfd - Set `min-height: 65px` for case when `height` can't be calculated.
All changes in this PR are related to `#menu .menuWrapper` element.
_This PR closes #741_
> fix: top menu not showing up in old browsers

- components/post/index.js
Add a missing boolean to make the recommendations loading when post page is opened.
> fix: recommendations load on post open

- js/_map.js
- Fix banner with app's download invitation not showing up
Described banner was firstly introduced in PR #565
> fix: apps download popup not showing

- tpls/main.js.tpl
- Move powerMonitor require
- Add shutdown event listener
> fix: app prevents macos shutdown

- js/notifications.js
- js/satolist.js
- Add check for `undefined` returned by `Notification.requestPermission()`.
The issue was found on latest DuckDuckGo browser. When try to authenticate, it's loading infinitely. If I reload the page it shows as authorized, however there are signs of something went wrong.
> fix: auth broken by notifications

- js/app.js
- Fix missed `JSON.stringify(...)` in #762.
> fix: user-agent is not string in logs

- components/videoCabinet/index.css
- components/videoCabinet/index.less
- js/peertube.js
- proxy16/peertube/index.js
- proxy16/proxy.js
- Added separate server for verified users — this includes both proxy changes and client changes (now "special" flag is sent if user has verified status, and proxy return special server for verified users. If there is no such server, usual servers are sent)
- Added a few mirroring servers for older instances, including big archive by Network_Support
- Fixed visualisation bug with the tag selecting window in video cabinet during video editing
- Fix roy selecting bug, that could produce inability for user to select roy
> patch: six new video servers and some fixes

- .github/workflows/build.release.yml
- Run `apt` command with `sudo`
- Run `apt` on **Ubuntu OS** matrix only (no apt on Windows and macOS)
This PR fixes release action that was broken after #842 changes introduced for RPM packages support.
> repo: fix release workflow

- proxy16/node/control.js
Update control.js to remove bad node options
> patch: remove bad proxy16 node options

- .github/workflows/night.bastyon.com.yml
The problem is caused by the unix assembly creating a nested dist directory for artifacts, and although the copy operation is `cp ./**/Bastyon*` should have taken into account all subdirectories - this does not happen. Therefore, I decided to divide the definition of information for the head.txt file and the unix assembly into different jobs
> repo: fix deploy workflow for linux binaries

- .github/actions/build.macos.yml
- .github/workflows/build.dev.yml
- .github/workflows/deploy.pulls.dev.yml
- .github/workflows/deploy.web.yml
- .github/workflows/night.bastyon.com.yml
- .github/workflows/night.test.bastyon.com.yml
- .github/workflows/pre.pocketnet.app.yml
- .github/workflows/test.pocketnet.app.yml
- components/leftpanel/index.css
- components/leftpanel/index.js
- components/leftpanel/index.less
- components/leftpanel/templates/footer.html
- components/userpage/index.css
- components/userpage/index.js
- components/userpage/index.less
- components/userpage/templates/contents.html
- localization/de.js
- localization/en.js
- localization/es.js
- localization/fr.js
- localization/it.js
- localization/kr.js
- localization/ru.js
- localization/zh.js
- minimize.js
- Add "built-from" badge for desktop UI
- Add "built-from" badge for mobile UI
- Support "copy on click"
- Refactor app info block
- Use vector logo with CSS3 filters applied
- When built from PR assembly action run, badge would contain **`base_commit_sha`** + **`run_unique_numeric_id`**.
- When built from release action runs, badge would contain **`base_commit_sha`**.
- When built from local station, badge would not appear. To show it, pass **`-sha=base_commit_sha`** and optionally **`-run=run_unique_numeric_id`** flags.
- Copied value would have next format - **`app_version`**-**`base_commit_sha`**-**`run_unique_numeric_id`**
> feat: show built version badge sha

- components/bestposts/index.js
- components/lenta/index.js
- components/post/index.js
- components/share/index.js
- components/share/templates/url.html
- components/socialshare2/index.js
- js/functions.js
- js/kit.js
- js/satolist.js
- js/vendor/plyr.js
- package-lock.json
- package.json
- Fix player not working with "short" type videos from YouTube
- Fix Brighteon player image preview
- Fix Vimeo player image preview
- Refactor `parseVideo()` function. Now it's better in the sense of readability and is more flexible
> patch: ipfs video links support and embed media player fixes

- components/share/templates/postline.html
- js/kit.js
- Add `itisembed()` to check if post has embedded player
- Add `itisipfs()` to check if post has embedded player with IPFS video
- Rewrite conditions for image upload UI
New conditions are allowing image upload UI for next cases...
- If post contains IPFS video. Then the uploaded image would be used for player thumbnail upload as was introduced in #1040
- If post doesn't contain video player, excluding IPFS player
Functions are documented in this PR [here](https://github.com/pocketnetteam/pocketnet.gui/pull/1043#issuecomment-1554254032).
Code is not efficient due to functions duplications.
> fix: image upload show conditions

- js/app.js
- package-lock.json
- package.json
- Forgotten condition was producing ghost update UI calls.
Done in context of #1030
> hotfix: update ui called on latest producing error

- components/post/index.js
- js/broadcaster.js
- js/satolist.js
- New method for Broadcaster to clear specific named events group
- Clear only network-stats event
Related to #1083
> fix: all tor events being dismounted and likes functionality

- components/userpage/index.css
- components/userpage/index.less
- components/userpage/templates/contents.html
- Show version on mobile anyway
When update is available, current mobile application version is not showing up. For debug reasons must be showed too
> fix: show version on mobile when update available

- .github/workflows/build.release.yml
- Allow to proceed release jobs if any of them failed to end
For some reason, our workflow has issues with macOS builds last weeks. This would allow us to build all but macOS at least and made the macOS build manually.
> repo: allow failed jobs on release

- proxy16/kit.js
- Remove 3 offline static nodes
- 140.99.153.138
- 172.83.108.41
- 172.83.108.40
- Add 6 online static nodes
- 95.31.45.162
- 79.143.35.233
- 109.197.196.106
- 65.21.252.135
- 178.217.159.221
- 65.21.56.203
This patch is based on network checks and Pocketnet.core official list.
https://github.com/pocketnetteam/pocketnet.core/blob/83418e8cc40cc672aaf9221ee4fa8b7856273f79/contrib/seeds/nodes_main.txt
> patch: update static nodes list

- proxy16/proxy.js
- Remove list from code
- Parsing testnet servers from remote list
Related to PR #1175
> patch: remote test peertube servers list

- package-lock.json
- package.json
- Set version to 0.8.85
Some users who updated to the faulty release 0.8.84 on April 8, 2024, are experiencing difficulties updating to the corrected version released on April 9, 2024, bearing the same version number. To address this issue, we are releasing version 0.8.85 as a resolution.
Related to PR's #1223 and #1175
> patch: set version to 0.8.85

- js/lib/apps/sdk.js
> fix: apps navigation

- components/application/index.js
> fix: hide miniappscnt when applicationfx is active

- proxy16/transports.js
This fixes a self-signed certificate error when using the Axios http client with socks-proxy-agent and self-signed certificates.
...
> fix: self signed certificate error

- proxy16/node/torcontrol.js
- proxy16/transports.js
This fixes the Tor socks port matches the Tor browser's socks port. The Tor browser uses the same socks proxy port to run Tor as Bastyon. Both apps have no fallback mechanism, so only the first app could use Tor. The second app could not run Tor.
...
> fix: change port of tor socks proxy
